// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/accounts": {
            "get": {
                "description": "Get all account list",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "List accounts",
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handler.AccountView"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new Discord account with the default concurrent limit and start its listener. Only guild_id, channel_id, and user_token are accepted.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Create account",
                "parameters": [
                    {
                        "description": "Account info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CreateAccountReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.AccountView"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/accounts/{id}": {
            "put": {
                "description": "Update the specified Discord account. At least one field must be provided. is_healthy is read-only and managed by listener checks; use the restart endpoint to re-check an account. While current_jobs is greater than 0, listener-changing fields (guild_id, channel_id, user_token, and disabling the account) are rejected; concurrent_limit can still be changed.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Update account",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Account info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.UpdateAccountReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.AccountView"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "Account not found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete the specified account and stop its listener. Accounts with active tasks cannot be deleted until current_jobs is 0.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Delete account",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "Account not found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/accounts/{id}/restart": {
            "post": {
                "description": "Restart the specified Discord account listener. is_healthy is managed by the server and will be updated after the listener verifies the account.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Restart account listener",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.AccountView"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "Account not found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tasks": {
            "get": {
                "description": "Get the task list",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "List tasks",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page size",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.TaskListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tasks/action": {
            "post": {
                "description": "Perform an action on a completed task (upscale, zoom_out_2x, zoom_out_1_5x, upscale_subtle, upscale_creative)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Perform task action",
                "parameters": [
                    {
                        "description": "Action request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.PerformTaskActionReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Action submitted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/service.TaskResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tasks/describe": {
            "post": {
                "description": "Create a Midjourney describe task that generates text prompts based on an image URL",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Create Describe task",
                "parameters": [
                    {
                        "description": "Describe task request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CreateDescribeTaskReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/service.TaskResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tasks/imagine": {
            "post": {
                "description": "Create a Midjourney image generation task based on the given prompt",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Create Imagine task",
                "parameters": [
                    {
                        "description": "Task request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CreateImagineTaskReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/service.TaskResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tasks/queue": {
            "get": {
                "description": "Get the list of tasks currently waiting to be processed",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Get queue list",
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/service.QueueStatus"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tasks/{task_id}": {
            "get": {
                "description": "Get task details by task ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Get task status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.TaskView"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Task not found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/live": {
            "get": {
                "description": "Check if the service is alive (simple ping)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "Service is alive",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.AccountView": {
            "type": "object",
            "properties": {
                "channel_id": {
                    "type": "string"
                },
                "concurrent_limit": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "current_jobs": {
                    "type": "integer"
                },
                "error_count": {
                    "type": "integer"
                },
                "guild_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_disabled": {
                    "type": "boolean"
                },
                "is_healthy": {
                    "type": "boolean"
                },
                "last_error": {
                    "type": "string"
                },
                "last_used_at": {
                    "type": "string"
                },
                "success_count": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "handler.CreateAccountReq": {
            "type": "object",
            "required": [
                "channel_id",
                "guild_id",
                "user_token"
            ],
            "properties": {
                "channel_id": {
                    "type": "string"
                },
                "guild_id": {
                    "type": "string"
                },
                "user_token": {
                    "type": "string"
                }
            }
        },
        "handler.CreateDescribeTaskReq": {
            "type": "object",
            "required": [
                "image_url"
            ],
            "properties": {
                "callback_url": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                }
            }
        },
        "handler.CreateImagineTaskReq": {
            "type": "object",
            "required": [
                "prompt"
            ],
            "properties": {
                "callback_url": {
                    "type": "string"
                },
                "prompt": {
                    "type": "string"
                }
            }
        },
        "handler.PerformTaskActionReq": {
            "type": "object",
            "required": [
                "action_type",
                "index",
                "task_id"
            ],
            "properties": {
                "action_type": {
                    "description": "Operation type",
                    "type": "string"
                },
                "callback_url": {
                    "type": "string"
                },
                "index": {
                    "description": "Index: 1-4",
                    "type": "integer"
                },
                "task_id": {
                    "description": "Original task ID",
                    "type": "string"
                }
            }
        },
        "handler.TaskListResponse": {
            "type": "object",
            "properties": {
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.TaskView"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "handler.TaskView": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "error_message": {
                    "type": "string"
                },
                "finished_at": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "oss_image_url": {
                    "type": "string"
                },
                "parent_task_id": {
                    "type": "string"
                },
                "progress": {
                    "type": "integer"
                },
                "prompt": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/model.TaskStatus"
                },
                "task_id": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/model.TaskType"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "handler.UpdateAccountReq": {
            "type": "object",
            "properties": {
                "channel_id": {
                    "type": "string"
                },
                "concurrent_limit": {
                    "type": "integer"
                },
                "guild_id": {
                    "type": "string"
                },
                "is_disabled": {
                    "type": "boolean"
                },
                "user_token": {
                    "type": "string"
                }
            }
        },
        "model.TaskStatus": {
            "type": "string",
            "enum": [
                "PENDING",
                "SUBMITTED",
                "IN_QUEUE",
                "PROCESSING",
                "SUCCESS",
                "FAILED",
                "TIMEOUT"
            ],
            "x-enum-varnames": [
                "TaskStatusPending",
                "TaskStatusSubmitted",
                "TaskStatusInQueue",
                "TaskStatusProcessing",
                "TaskStatusSuccess",
                "TaskStatusFailed",
                "TaskStatusTimeout"
            ]
        },
        "model.TaskType": {
            "type": "string",
            "enum": [
                "IMAGINE",
                "DESCRIBE",
                "UPSCALE",
                "ZOOM_OUT_2X",
                "ZOOM_OUT_1_5X",
                "UPSCALE_SUBTLE",
                "UPSCALE_CREATIVE"
            ],
            "x-enum-comments": {
                "TaskTypeDescribe": "Describe image",
                "TaskTypeUpscale": "Upscale",
                "TaskTypeUpscaleCreative": "Upscale (Creative)",
                "TaskTypeUpscaleSubtle": "Upscale (Subtle)",
                "TaskTypeZoomOut1_5x": "Zoom Out 1.5x",
                "TaskTypeZoomOut2x": "Zoom Out 2x"
            },
            "x-enum-descriptions": [
                "",
                "Describe image",
                "Upscale",
                "Zoom Out 2x",
                "Zoom Out 1.5x",
                "Upscale (Subtle)",
                "Upscale (Creative)"
            ],
            "x-enum-varnames": [
                "TaskTypeImagine",
                "TaskTypeDescribe",
                "TaskTypeUpscale",
                "TaskTypeZoomOut2x",
                "TaskTypeZoomOut1_5x",
                "TaskTypeUpscaleSubtle",
                "TaskTypeUpscaleCreative"
            ]
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {},
                "detail": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "service.ProcessingQueueItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "finished_at": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "oss_image_url": {
                    "type": "string"
                },
                "parent_task_id": {
                    "type": "string"
                },
                "progress": {
                    "type": "integer"
                },
                "prompt": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/model.TaskStatus"
                },
                "task_id": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/model.TaskType"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "service.QueueItem": {
            "type": "object",
            "properties": {
                "image_url": {
                    "type": "string"
                },
                "kind": {
                    "$ref": "#/definitions/service.QueueMessageKind"
                },
                "parent_task_id": {
                    "type": "string"
                },
                "prompt": {
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                }
            }
        },
        "service.QueueMessageKind": {
            "type": "string",
            "enum": [
                "imagine",
                "describe",
                "action"
            ],
            "x-enum-varnames": [
                "QueueMessageKindImagine",
                "QueueMessageKindDescribe",
                "QueueMessageKindAction"
            ]
        },
        "service.QueueStatus": {
            "type": "object",
            "properties": {
                "processing_count": {
                    "type": "integer"
                },
                "processing_tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.ProcessingQueueItem"
                    }
                },
                "queue_length": {
                    "type": "integer"
                },
                "waiting_in_queue": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.QueueItem"
                    }
                }
            }
        },
        "service.TaskResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "$ref": "#/definitions/model.TaskStatus"
                },
                "task_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Midjourney Proxy API",
	Description:      "Midjourney Proxy API Service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
